config/routes.rb
Rails.application.routes.draw do
  root 'platforms#index'

  resources :platforms do
    member do
      get 'update_all_markets'
    end
    resources :markets
  end

  resources :markets do
    resources :tickers
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/market.rb
class Market < ApplicationRecord
  belongs_to :platform
  has_many :tickers, dependent: :destroy
  accepts_nested_attributes_for :tickers
  validates :market_name, presence: true,
                    length: { minimum: 5 }
  after_create :update_market_summary

  def self.get_market_name_long(market_name, getmarkets_querydata)
    #find matching match_name for getmarkets query
    @currency = market_name.split("-")[-1] #default coin name if not available
    getmarkets_querydata.map do |m|
      if market_name == m["MarketName"]
        @currency = m["MarketCurrencyLong"]
      end
    end
    @currency
  end

  def self.percentage_difference(number1, number2)
    (number1 / number2 * 100 - 100).round(2)
  end

  def self.sign(number)
    #return string "positive" or "negative"
    (number < 0) ? "negative" : "positive"
  end

  def update_market_summary
    url = "https://bittrex.com/api/v1.1/public/getmarketsummary?market=#{market_name}"
    response = RestClient.get(url)
    parsed_body = JSON.parse(response.body)
    querydata = parsed_body["result"] if parsed_body["success"]

    # only update long market name the first time
    if !self.attributes.key?(market_currency_name)
      # This query to get long market name
      url = "https://bittrex.com/api/v1.1/public/getmarkets"
      response = RestClient.get(url)
      parsed_body = JSON.parse(response.body)
      querydata_markets = parsed_body["result"] if parsed_body["success"]
      @currency_name = Market.get_market_name_long(market_name, querydata_markets)
    end
    self.attributes = {
      high: querydata[0]["High"],
      low: querydata[0]["Low"],
      last: querydata[0]["Last"],
      volume: querydata[0]["Volume"],
      base_volume: querydata[0]["BaseVolume"],
      bid: querydata[0]["Bid"],
      ask: querydata[0]["Ask"],
      prev_day: querydata[0]["PrevDay"],
      created: querydata[0]["Created"],
      open_buy_orders: querydata[0]["OpenBuyOrders"],
      open_sell_orders: querydata[0]["OpenSellOrders"],
      market_currency_name: @currency_name
    }
  end

  def self.get_market_summaries
    url = "https://bittrex.com/api/v1.1/public/getmarketsummaries"
    response = RestClient.get(url)
    parsed_body = JSON.parse(response.body)
    querydata_summaries = parsed_body["result"] if parsed_body["success"]

    # This query to get long market name
    url = "https://bittrex.com/api/v1.1/public/getmarkets"
    response = RestClient.get(url)
    parsed_body = JSON.parse(response.body)
    querydata_markets = parsed_body["result"] if parsed_body["success"]

    markets = []
    querydata_summaries.each do |market|
      markets << {
      market_name: market["MarketName"],
      high: market["High"],
      low: market["Low"],
      volume: market["Volume"],
      last: market["Last"],
      base_volume: market["BaseVolume"],
      bid: market["Bid"],
      ask: market["Ask"],
      open_buy_orders: market["OpenBuyOrders"],
      open_sell_orders: market["OpenSellOrders"],
      prev_day: market["PrevDay"],
      created: market["Created"],
      market_currency_name: get_market_name_long(market["MarketName"], querydata_markets),
      change: percentage_difference(market["PrevDay"], market["Last"]),
      change_sign: sign(percentage_difference(market["PrevDay"], market["Last"]))}
    end
    return markets
  end
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_many :markets, dependent: :destroy
  validates :name, presence: true
  accepts_nested_attributes_for :markets

  def self.update_market_summaries(platform_id)
    url = "https://bittrex.com/api/v1.1/public/getmarketsummaries"
    response = RestClient.get(url)
    parsed_body = JSON.parse(response.body)
    querydata_summaries = parsed_body["result"] if parsed_body["success"]
    querydata_summaries.each do |m|
      @platform = Platform.find(platform_id)
      market = @platform.markets.find_by(market_name: m["MarketName"])
      if market != nil
        market.attributes = {
          high: m["High"],
          low: m["Low"],
          last: m["Last"],
          volume: m["Volume"],
          base_volume: m["BaseVolume"],
          bid: m["Bid"],
          ask: m["Ask"],
          prev_day: m["PrevDay"],
          created: m["Created"],
          open_buy_orders: m["OpenBuyOrders"],
          open_sell_orders: m["OpenSellOrders"]}
        market.save
      end
    end
  end
end

app/models/ticker.rb
class Ticker < ApplicationRecord
  belongs_to :market

  def self.get_latest_ticker(market_name)
    url = "https://bittrex.com/api/v1.1/public/getticker?market=#{market_name}"
    response = RestClient.get(url)
    parsed_body = JSON.parse(response.body)
    querydata = parsed_body["result"] if parsed_body["success"]
    ticker_data = {
      bid: querydata["Bid"],
      ask: querydata["Ask"],
      last: querydata["Last"]}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  def index
    #show available markets
    @platform = Platform.find(params[:platform_id])
    @markets = @platform.markets
    market_list = Market.get_market_summaries
    @markets.each do |market| # remove from list if already added
      market_list.delete_if { |m| m[:market_name] == market.market_name}
    end
    @available_markets = market_list
  end

  def show
    @market = Market.find(params[:id])
  end

  def new
    @market = Market.new
  end

  def create
    @platform = Platform.find(params[:platform_id])
    @market = @platform.markets.create(market_params)
    if @market.save
      redirect_to platform_path(@platform)
    end
  end

  def update
    @market = Market.find(params[:id])
    @market.update_market_summary
    @market.save
    redirect_to @market.platform
  end

  def destroy
    @market = Market.find(params[:id])
    @market.destroy
    redirect_to @market.platform
  end

  private
    def market_params
      params.require(:market).permit(:market_name)
    end
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  def index
    @platforms = Platform.all
  end

  def show
    @platform = Platform.find(params[:id])
  end

  def new
    @platform = Platform.new
  end

  def create
    @platform = Platform.new(platform_params)
    if @platform.save
      redirect_to @platform
    else
      render 'new'
    end
  end

  def update_all_markets
    UpdateMarketSummariesWorker.perform_async(params[:id])
    @platform = Platform.find(params[:id])
    redirect_to @platform
  end

  def destroy
    @platform = Platform.find(params[:id])
    @platform.destroy

    redirect_to platforms_path
  end

  private
    def platform_params
      params.require(:platform).permit(:name, :website)
    end
end

app/controllers/tickers_controller.rb
class TickersController < ApplicationController

  def create
    @market = Market.find(params[:market_id])
    @latest_ticker = Ticker.get_latest_ticker(@market.market_name)
    @previous_ticker = @market.tickers.last       #check if there was a ticker to begin with
    if (@previous_ticker == NIL) or
       (@previous_ticker.ask != @latest_ticker[:ask] or #check if new ticker is different
        @previous_ticker.bid != @latest_ticker[:bid] or
        @previous_ticker.last != @latest_ticker[:last])
      @ticker = @market.tickers.create
      @ticker.attributes = {
        ask: @latest_ticker[:ask],
        bid: @latest_ticker[:bid],
        last: @latest_ticker[:last]}
      @ticker.save
      redirect_to @ticker.market
    else
      redirect_to @previous_ticker.market
    end
  end

  def update
     @ticker = @market.tickers.create
  end

  def destroy
    @ticker = Ticker.find(params[:id])
    @ticker.destroy
    redirect_to @ticker.market
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Realtime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/markets/index.html.erb
<%= javascript_include_tag "sorttable" %>
<%= stylesheet_link_tag "responsivetable" %>

<h1>Available Markets:</h1>

<table class="sortable rwd-table">
  <tr>
    <th>Market</th>
    <th>Price</th>
    <th>Volume</th>
    <th>Change</th>
    <th>Name</th>
  </tr>
  <% @available_markets.each do |market| %>
    <tr>
      <td><%= link_to market[:market_name], platform_markets_path(@platform,
                      :market => {:market_name => market[:market_name]}),
                      :method => :post %></td>
      <td style="text-align:right"><%= "%1.8f" % market[:last] %></td>
      <td style="text-align:right"><%= "%1.3f" % market[:base_volume] %></td>
      <td style="text-align:right" class="<%= market[:change_sign] %>"><%= "%+.2f" % market[:change] %></td>
      <td><%= market[:market_currency_name] %></td>
    </tr>
    <% end %>
</table>

app/views/markets/new.html.erb
<h1>Add new market</h1>

<% if @market.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@market.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @market.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for :market, url: markets_path do |f| %>
  <p>
    <%= f.label :market %><br>
    <%= f.text_field :market_name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', markets_path %>

app/views/markets/show.html.erb
<%= javascript_include_tag "sorttable" %>
<%= stylesheet_link_tag "responsivetable" %>
<p>
  <strong>Market Name:</strong>
  <%= @market.market_name %>
</p>
<p>
  <strong>High:</strong>
  <%= @market.high %></br>
  <strong>Low:</strong>
  <%= @market.low %></br>
  <strong>Volume:</strong>
  <%= @market.volume %></br>
  <strong>Base Volume:</strong>
  <%= @market.base_volume %></br>
  <strong>Previous day:</strong>
  <%= @market.prev_day %></br>
  <strong>Open buy orders:</strong>
  <%= @market.open_buy_orders %></br>
  <strong>Open sell orders:</strong>
  <%= @market.open_sell_orders %></br>
  <hr>

  <p>
    <strong>Last tickers</strong>
  </p>
  <p>
    <%= link_to 'Update ticker', [@market, Ticker], :method => :create %>
  </p>
  <table class="rwd-table">
    <tr>
      <th>Time</th>
      <th>Bid</th>
      <th>Ask</th>
      <th>Last</th>
    </tr>
    <% @market.tickers.reverse_each do |ticker| %>
    <tr>
      <td><%= ticker.created_at %></td>
      <td><%= "%1.8f" % ticker.bid %></td>
      <td><%= "%1.8f" % ticker.ask %></td>
      <td><%= "%1.8f" % ticker.last %></td>
    </tr>
    <% end %>
  </table>
  <%= link_to 'Back', platform_path(@market.platform) %>

app/views/platforms/_market_overview.erb
<div class=“market_overview”>
  <tr>
    <td><%= market_overview.market_name %></td>
    <td style="text-align:right"><%= "%1.8f" % market_overview.last %></td>
    <td style="text-align:right"><%= "%1.3f" % market_overview.base_volume %></td>
    <td style="text-align:right" class="<%= Market.sign(Market.percentage_difference(market_overview.prev_day, market_overview.last)) %>">
                                        <%= "%+.2f" % Market.percentage_difference(market_overview.prev_day, market_overview.last) %></td>
    <td><%= market_overview.market_currency_name %></td>
    <td><%= link_to 'More details', [market_overview.platform, market_overview] %></td>
    <td><%= link_to 'Update', [market_overview.platform, market_overview],
            :method => :put %></td>
    <td><%= link_to 'Delete', [market_overview.platform, market_overview],
            method: :delete,
            data: { confirm: 'Are you sure?' } %></td>
   </tr>
 </div>

app/views/platforms/index.html.erb
<script type="text/javascript" src="node_modules\node.bittrex.api\node.bittrex.api.js"></script>
<h1>Platforms</h1>

<%= link_to 'Add new platform', new_platform_path %>

<table>
  <tr>
    <th>Platform</th>
    <th>URL</th>
  </tr>

  <% @platforms.each do |platform| %>
    <tr>
      <td><%= platform.name %></td>
      <td><%= platform.website %></td>
      <td><%= link_to 'Show markets', platform_path(platform) %></td>
      <td><%= link_to 'Delete', platform_path(platform),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
     </tr>
  <% end %>
</table>

app/views/platforms/new.html.erb
<h1> Add new platform</h1>
<%= form_for :platform, url: platforms_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/platforms/show.html.erb
<%= javascript_include_tag "sorttable" %>
<%= stylesheet_link_tag "responsivetable" %>

<h1>Platform: <a href="http://<%=@platform.website %>"><%= @platform.name %></a></h1>
<%= button_to 'Update all markets', update_all_markets_platform_path(@platform), :method => 'get' %>
<hr>
<table id="market-overview-table" class="sortable rwd-table">
  <tr>
    <th>Market</th>
    <th>Price</th>
    <th>Volume</th>
    <th>Change</th>
    <th>Name</th>
  </tr>
  <%= render partial: "market_overview", collection: @platform.markets %>
</table>
<hr>
<h2>Add market</h2>
<%= link_to 'View available markets', platform_markets_path(@platform) %>
<%= form_for([@platform, @platform.markets.build]) do |f| %>
  <p>
    <%= f.label :market %><br>
    <%= f.text_field :market_name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', platforms_path %>